- name: install nginx web server
  hosts: servers
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: stop nginx server
      ansible.builtin.service:
        name: nginx
        state: stopped
        enabled: no
