- name: install nginx web server
  hosts: servers
  become: yes
  gather_facts: no
  tasks:

    block:
      - name: install nginx
        ansible.builtin.package:
          name: nginx
          state: present

      - name: stop nginx server
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: yes

    rescue:
      - name: print error message
        ansible.builtin.debug:
          msg: "failed to start nginx server"

    always:
      - name: Execution completed
        ansible.builtin.debug:
          msg: "Execution of block completed"


          
