---
- name: Read data from Linux machine
  hosts: test
  gather_facts: true
  tasks:

    - name: Print hostname
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname}}"
  
    - name: Print OS distribution
      ansible.builtin.debug:
        msg: "The OS distribution is {{ ansible_facts['distribution'] }} version {{ ansible_facts['distribution_version'] }}"

    - name: Print ip address 
      ansible.builtin.debug:
        msg: "IP address : {{ ansible_facts['default_ipv4']['address'] }}"

    - name: Check available disk space on root directory
      ansible.builtin.shell: df -h / | awk 'NR==2 {print $4}'
      register: disk_space

    - name: Print available disk space
      ansible.builtin.debug:
        msg: "Available space on / is {{ disk_space.stdout }}"

    - name: Check Disk usage
      ansible.builtin.shell: df -h --output=source,size,used,avilable,percentage,target | column -target
      register: disk_space

    - name: Print Disk usage
      ansible.builtin.debug:
        msg: "{{ disk_space.stdout_lines }}""
